# Generated by Django 4.2.7 on 2023-12-02 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_remove_supplier_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
    ]
