# Generated by Django 4.2.7 on 2023-11-28 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=100)),
                ('unique_stock', models.BigIntegerField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_day', models.DateField()),
                ('total_products', models.BigIntegerField()),
                ('invetory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managament.inventory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managament.product')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='products',
            field=models.ManyToManyField(related_name='products', through='managament.InventoryDetail', to='managament.product'),
        ),
    ]
