# Generated by Django 4.2.7 on 2023-12-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorydetail',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
