# Generated by Django 4.2.7 on 2023-12-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managament', '0002_inventorydetail_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='products',
            field=models.ManyToManyField(related_name='inventory_products', through='managament.InventoryDetail', to='managament.product'),
        ),
    ]
