# Generated by Django 4.2.7 on 2023-12-13 00:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managament', '0003_alter_inventory_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorydetail',
            name='delivery_day',
        ),
        migrations.RemoveField(
            model_name='inventorydetail',
            name='total_products',
        ),
        migrations.AddField(
            model_name='inventory',
            name='delivery_day',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='inventory',
            name='total_products',
            field=models.BigIntegerField(default=0),
        ),
    ]
