# Generated by Django 4.2.7 on 2023-12-13 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managament', '0004_remove_inventorydetail_delivery_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorydetail',
            old_name='invetory',
            new_name='inventory',
        ),
    ]
