# Generated by Django 4.2.7 on 2023-12-14 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_student'),
        ('managament', '0005_rename_invetory_inventorydetail_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorydetail',
            name='supplier',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.supplier'),
        ),
    ]
