# Generated by Django 4.2.7 on 2023-11-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Last name')),
                ('isActive', models.BooleanField(default=True)),
                ('isAdmin', models.BooleanField(default=False)),
                ('profile', models.CharField(choices=[('1', 'administrador'), ('2', 'operador'), ('3', 'inspector'), ('4', 'cliente')], max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
