# Generated by Django 4.2.7 on 2023-12-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_username_alter_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.CharField(choices=[('1', 'administrator'), ('2', 'employee'), ('3', 'student')], max_length=1),
        ),
    ]
